#!/bin/bash
apm install Sublime-Style-Column-Selection
apm install atom-beautify
apm install atom-jade
apm install busy-signal
apm install copy-path
apm install editorconfig
apm install emmet
apm install file-icons
apm install highlight-selected
apm install intentions
apm install language-babel
apm install language-docker
apm install language-latex
apm install language-pug
apm install language-vue
apm install linter
apm install linter-sass-lint
apm install linter-ui-default
apm install minimap
apm install monokai
apm install multi-cursor
apm install pigments
apm install prettier-atom
apm install teletype
