#!/bin/bash
apm install Sublime-Style-Column-Selection
apm install atom-beautify
apm install atom-jade
apm install atom-typescript
apm install busy-signal
apm install copy-path
apm install editorconfig
apm install emmet
apm install file-icons
apm install git-blame
apm install git-control
apm install git-plus
apm install highlight-selected
apm install intentions
apm install language-babel
apm install language-docker
apm install language-jade
apm install language-latex
apm install language-pug
apm install language-vue
apm install linter
apm install linter-eslint
apm install linter-jshint
apm install linter-pug
apm install linter-sass-lint
apm install linter-tslint
apm install linter-ui-default
apm install markdown-preview-plus
apm install merge-conflicts
apm install minimap
apm install monokai
apm install multi-cursor
apm install pigments
apm install prettier-atom
apm install teletype
